-- 커뮤니티 게시글 테이블 생성
CREATE TABLE IF NOT EXISTS public.community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author_name TEXT NOT NULL,
    author_email TEXT NOT NULL,
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 댓글 테이블 생성
CREATE TABLE IF NOT EXISTS public.community_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES public.community_posts(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    author_email TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.community_comments ENABLE ROW LEVEL SECURITY;

-- 게시글 조회 권한: 누구나 가능
CREATE POLICY "Allow public select on community_posts" ON public.community_posts
    FOR SELECT USING (true);

-- 게시글 작성 권한: 인증된 사용자만 가능
CREATE POLICY "Allow authenticated insert on community_posts" ON public.community_posts
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 게시글 삭제/수정 권한: 작성자 본인 또는 관리자만 가능
CREATE POLICY "Allow update/delete for authors and admins on community_posts" ON public.community_posts
    FOR ALL USING (
        auth.email() = author_email OR 
        auth.email() IN ('theonsil@gmail.com', 'admin@theonsil.co.kr', 'theonsilofficial@gmail.com')
    );

-- 댓글 조회 권한: 누구나 가능
CREATE POLICY "Allow public select on community_comments" ON public.community_comments
    FOR SELECT USING (true);

-- 댓글 작성 권한: 인증된 사용자만 가능
CREATE POLICY "Allow authenticated insert on community_comments" ON public.community_comments
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 댓글 삭제 권한: 작성자 본인 또는 관리자만 가능
CREATE POLICY "Allow delete for authors and admins on community_comments" ON public.community_comments
    FOR DELETE USING (
        auth.email() = author_email OR 
        auth.email() IN ('theonsil@gmail.com', 'admin@theonsil.co.kr', 'theonsilofficial@gmail.com')
    );

-- Realtime 활성화 (선택 사항)
ALTER PUBLICATION supabase_realtime ADD TABLE community_posts;
ALTER PUBLICATION supabase_realtime ADD TABLE community_comments;
