-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgBo0Ei/4NtdkARRzI
N6kNETzK3T4jZIhRWSdqSPrzIMKgCgYIKoZIzj0DAQehRANCAARmfgsYoOgGVYrP
lqTlIB2k7AI9NWzT+/J4SjvrYZmnst6xEMYU30refgoCxztaw9bR9d61iQnkYD/x
vZ2c41Ci
-----END PRIVATE KEY-----