require_relative '../../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# Add custom cocoapods here

target 'App' do
  capacitor_pods
  # Add your Pods here
end
